project:
  type: website
  output-dir: docs
  resources:
    - "slides/*.pdf"
    - "slides/*.html"

website:
  title: "Scientific workflows: Tools and Tips 🛠️"
  description: "A lecture series by Selina Baldauf"

  page-footer:
    left: "The footer on the left"
    right: "The footer on the right"

  navbar:
    pinned: true
    right:
      - text: Sessions
        menu:
          - text: 01 - What they forgot to teach you about R
            href: sessions/01_what_they_forgot.qmd
          - text: 02 - Reproducible documents with Quarto
            href: sessions/02_quarto.qmd
          - text: 03 - Version control with Git
            href: sessions/03_git.qmd
      - icon: github
        href: https://github.com/selinaZitrone/lecture_series


format:
  html:
    embed-resources: true
    theme:
      light: [flatly, style/theme.scss]
      dark: [darkly, style/theme.scss]
    css: style/style.css
    toc: true
    code-copy: true
    code-overflow: wrap



